// Code generated by Kitex v0.4.4. DO NOT EDIT.

package usermessservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"runedance_douyin/kitex_gen/usermess"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserRegister(ctx context.Context, req *usermess.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *usermess.DouyinUserRegisterResponse, err error)
	UserLogin(ctx context.Context, req *usermess.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *usermess.DouyinUserLoginResponse, err error)
	GetUserMess(ctx context.Context, req *usermess.DouyinUserRequest, callOptions ...callopt.Option) (r *usermess.DouyinUserResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUsermessServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUsermessServiceClient struct {
	*kClient
}

func (p *kUsermessServiceClient) UserRegister(ctx context.Context, req *usermess.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *usermess.DouyinUserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRegister(ctx, req)
}

func (p *kUsermessServiceClient) UserLogin(ctx context.Context, req *usermess.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *usermess.DouyinUserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogin(ctx, req)
}

func (p *kUsermessServiceClient) GetUserMess(ctx context.Context, req *usermess.DouyinUserRequest, callOptions ...callopt.Option) (r *usermess.DouyinUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMess(ctx, req)
}
