// Code generated by Kitex v0.4.4. DO NOT EDIT.

package recommendservice

import (
	server "github.com/cloudwego/kitex/server"
	recommend "runedance_douyin/cmd/recommend/kitex_gen/recommend"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler recommend.RecommendService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
