// Code generated by hertz generator.

package main

import (
	handler "runedance_douyin/cmd/video_player/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/fileapi/:type/:storageID/", handler.Play)
	// your code ...
}
