// Code generated by hertz generator.

package main

import (
	"runedance_douyin/cmd/api/biz/rpc"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	rpc.Init()
}
func main() {
	Init()
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"), server.)
	//h.Use(mw.MyJWT())

	register(h)
	h.Spin()
}
