DSN: "root:123456@tcp(localhost:3306)/douyin?charset=utf8&parseTime=True&loc=Local"
Table:
  Realation:
    rpc
  User:
    uesr
  Videos:
    videos
  #这里自己加表名吧
ServiceName:
    relation_service
etcd_address:
    127.0.0.1:2379
RabiitMQ:
    url: amqp://guest:guest@localhost:5672/
