DSN: "root:123456@tcp(localhost:3306)/douyin?charset=utf8&parseTime=True&loc=Local"
Table:
  Realation:
    relation
  User:
    uesr
  Videos:
    videos
  #这里自己加表名吧
ServiceName:
    relation_service
etcd_address:
    127.0.0.1:2379
RabiitMQ:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
